barrier_loss_weight: 0.0001
barrier_order: 2
barrier_order_increase_iter: 1000
geometric_loss_weight: 1.0
grad_clip_value: 0.01
initial_tetmesh_path: ../mesh_data/s.1.obj
learning_rate: 0.01
log_interval: 10
num_iterations: 2000
output_path: results/shape_fitting
save_interval: 100
smoothness_loss_weight: 0.0001
target_mesh_path: jro_head_025.obj
